name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date '+%Y%m%d%H%M%S')"
    - name: Build the Docker image
      env:
        TAG: ${{ steps.date.outputs.date }}
      run: docker build . --file Dockerfile --tag peez/playground:$TAG
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push the Docker image - versioned
      env:        
        TAG: ${{ steps.date.outputs.date }}
      run: docker push peez/playground:$TAG
    - name: Push the Docker image - latest
      env:
        TAG: ${{ steps.date.outputs.date }}
      run: docker tag peez/playground:$TAG peez/playground:latest && docker push peez/playground:latest
